<a href="https://colab.research.google.com/github/gonulsinem/Deep-Learning---Derin-Ogrenme/blob/main/PyTorch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
#kutuphaneler import edildi

In [4]:
# autograd paketi otomatik farklilasma saglar
# Zincir kuralını uygularken kısmi türevleri hesaplar
x = torch.rand(5, requires_grad=True)
print(x)

y = x+3
print(y)

print(x.grad_fn)
print(y.grad_fn)

tensor([0.2056, 0.1412, 0.5449, 0.4543, 0.8524], requires_grad=True)
tensor([3.2056, 3.1412, 3.5449, 3.4543, 3.8524], grad_fn=<AddBackward0>)
None


In [5]:
print(y,'\n')
z = y*y*3
print(z,'\n')
z = z.mean()
print(z)

tensor([3.2056, 3.1412, 3.5449, 3.4543, 3.8524], grad_fn=<AddBackward0>) 

tensor([30.8280, 29.6019, 37.6980, 35.7962, 44.5220], grad_fn=<MulBackward0>) 

tensor(35.6892, grad_fn=<MeanBackward0>)


In [7]:
z.backward()
print(x.grad) #dz/dx -> x'e gore kısmi turevi

tensor([3.8467, 3.7695, 4.2538, 4.1451, 4.6228])


In [12]:
x = torch.rand(5, requires_grad=True)
print(x,'\n')

y = x*2
for i in range(10):
  y = y*2

print(y)
print(y.shape)  

tensor([0.1890, 0.0077, 0.8011, 0.1491, 0.3703], requires_grad=True) 

tensor([ 387.1010,   15.7023, 1640.7482,  305.3612,  758.4712],
       grad_fn=<MulBackward0>)
torch.Size([5])


In [13]:
a = torch.randn(2,2)
print(a.requires_grad)

False


In [16]:
b = ((a*2) / (a-2))
print(b)
print(b.grad_fn)

tensor([[ 0.4867,  0.1739],
        [-1.4114, -0.2140]])
None


In [20]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [21]:
b = (a * a).sum()
print(b.grad_fn)

In [22]:
a = torch.randn(3,3, requires_grad=True)
print(a.requires_grad)

True


In [23]:
b = a.detach() # gradyan hesaplamasi olmadan ayni tensoru tekrar aldi
print(b.requires_grad)

False


In [29]:
k = torch.randn(2,2, requires_grad=True)
print(k.requires_grad)
with torch.no_grad():
  print((x ** 2).requires_grad)

print('\n****')
print(k)
print(x)
print(x.grad_fn)
print(x.requires_grad)


True
False

****
tensor([[-1.1938,  1.9829],
        [ 1.0465,  1.4674]], requires_grad=True)
tensor([[-0.3120,  0.7854],
        [ 0.5602, -0.2539]], requires_grad=True)
None
True


In [40]:
# backward() grad attribute ile toplar
weights = torch.ones(4, requires_grad=True)

for epoch in range(5):
  model_output = (weights*5).sum()
  model_output.backward()

  print(weights.grad)

  with torch.no_grad():
    weights -= 0.2 * weights.grad
  weights.grad.zero_() #agirlikklar ve ciktiyi ekler    
  #optimizer zero_grad() yontemiyle hesaplama yapar.

print('\n ***** \n')
print(weights)
print(model_output)  

tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])
tensor([5., 5., 5., 5.])

 ***** 

tensor([-4., -4., -4., -4.], requires_grad=True)
tensor(-60., grad_fn=<SumBackward0>)
