<a href="https://colab.research.google.com/github/gonulsinem/Deep-Learning---Derin-Ogrenme/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* PyTorch tensorlere dayanir.
* Scalar 0 boyutlu, vector 1 boyutlu, matris 2 boyutlu tensordur.
* scalar, vector, matrix, tensor

In [1]:
import torch

In [38]:
import numpy as np

In [2]:
x1 = torch.empty(1) #scalar, skaler
x1

tensor([-9.8004e-07])

In [3]:
x2 = torch.empty(3) #vektor, vector
x2

tensor([-9.8004e-07,  3.0838e-41,  5.0447e-44])

In [4]:
x3 = torch.empty(2,3) # 2x3 boyutunda matris, matrix
x3

tensor([[-9.8004e-07,  3.0838e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
x4 = torch.empty(3,2) # 3x2 boyutunda matrix
x4

tensor([[-9.8004e-07,  3.0838e-41],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [6]:
x5 = torch.empty(2,2,3) # 3 boyutlu tensor
x5

tensor([[[-9.8004e-07,  3.0838e-41,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [7]:
x6 = torch.empty(2,2,3,3) # 4 boyutlu tensor
x6

tensor([[[[-9.5270e-07,  3.0838e-41,  0.0000e+00],
          [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [-9.8941e-07,  3.0838e-41,  0.0000e+00],
          [ 0.0000e+00,  2.8026e-45,  0.0000e+00]]],


        [[[ 2.8026e-45,  0.0000e+00,  4.2039e-45],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  4.2039e-45,  0.0000e+00],
          [ 1.4013e-45,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])

In [8]:
x7 = torch.rand(5,3) # 0-1 arasinda deger alir.
x7

tensor([[0.1813, 0.4377, 0.7402],
        [0.1514, 0.8202, 0.6959],
        [0.4591, 0.0578, 0.3788],
        [0.6296, 0.5801, 0.5658],
        [0.6537, 0.4431, 0.2541]])

In [9]:
x7 = torch.zeros(2,3)  # 2x3 boyutunda matrisi 0 ile doldurur.
x7

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x7 = torch.ones(5,3) # 5x3 boyutunda matrisi 1 ile doldurur.
x7

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
print(x6.size())
print(x7.size()) # boyutu
print(x7.dtype) # verinin tipi

torch.Size([2, 2, 3, 3])
torch.Size([5, 3])
torch.float32


In [12]:
x8 = torch.tensor([2.5, 3])
print(x8.size())

torch.Size([2])


In [13]:
# requires_grad, gradyanlari hesaplar daha sonra optimize ederiz
x9 = torch.tensor([2.5, 3], requires_grad=True)
x9

tensor([2.5000, 3.0000], requires_grad=True)

In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.9632, 0.2849],
        [0.0736, 0.6580]])
tensor([[0.6474, 0.6525],
        [0.2231, 0.9060]])


In [15]:
z = x+y
print(z)
print(torch.add(x,y))

tensor([[1.6106, 0.9373],
        [0.2968, 1.5640]])
tensor([[1.6106, 0.9373],
        [0.2968, 1.5640]])


In [16]:
z = x-y
print(z)
print(torch.sub(x,y))

tensor([[ 0.3159, -0.3676],
        [-0.1495, -0.2481]])
tensor([[ 0.3159, -0.3676],
        [-0.1495, -0.2481]])


In [17]:
z = x*y
print(z)
print(torch.mul(x,y))

tensor([[0.6236, 0.1859],
        [0.0164, 0.5961]])
tensor([[0.6236, 0.1859],
        [0.0164, 0.5961]])


In [18]:
z = x/y
print(z)
print(torch.div(x,y))

tensor([[1.4880, 0.4366],
        [0.3299, 0.7262]])
tensor([[1.4880, 0.4366],
        [0.3299, 0.7262]])


In [21]:
# sciling - olcekleme
# pandas olcekleme mantigiyla ayni
x = torch.rand(6,4)
print('x',x)
print(x[:,0])
print(x[1,:])
print(x[1,1])
print('Tümü..:\n',x[:,:])


x tensor([[0.9399, 0.1715, 0.3722, 0.5972],
        [0.6951, 0.1911, 0.5460, 0.1167],
        [0.4917, 0.3019, 0.0977, 0.7682],
        [0.0167, 0.4180, 0.7429, 0.4362],
        [0.4085, 0.3057, 0.1967, 0.3333],
        [0.8331, 0.9817, 0.4757, 0.9505]])
tensor([0.9399, 0.6951, 0.4917, 0.0167, 0.4085, 0.8331])
tensor([0.6951, 0.1911, 0.5460, 0.1167])
tensor(0.1911)
Tümü..:
 tensor([[0.9399, 0.1715, 0.3722, 0.5972],
        [0.6951, 0.1911, 0.5460, 0.1167],
        [0.4917, 0.3019, 0.0977, 0.7682],
        [0.0167, 0.4180, 0.7429, 0.4362],
        [0.4085, 0.3057, 0.1967, 0.3333],
        [0.8331, 0.9817, 0.4757, 0.9505]])


In [24]:
print(x[1,1])  #tensorde 1 deger var
print(x[1,1].item())

tensor(0.1911)
0.1910584568977356


In [45]:
# torch.view() ile reshape yapilir
x = torch.rand(4,4)
print(x)

tensor([[0.1144, 0.6809, 0.3633, 0.0272],
        [0.5512, 0.6424, 0.2738, 0.9107],
        [0.4596, 0.3970, 0.8267, 0.4072],
        [0.6491, 0.9266, 0.5770, 0.4905]])


In [46]:
y = x.view(16) # 4x4 boyutundaki matris 16x1 boyutunda vektore donustu 
print(y)

tensor([0.1144, 0.6809, 0.3633, 0.0272, 0.5512, 0.6424, 0.2738, 0.9107, 0.4596,
        0.3970, 0.8267, 0.4072, 0.6491, 0.9266, 0.5770, 0.4905])


In [47]:
z = x.view(-1,8) # -1'de boyut otomatik olarak belirlenir.
print(z)

tensor([[0.1144, 0.6809, 0.3633, 0.0272, 0.5512, 0.6424, 0.2738, 0.9107],
        [0.4596, 0.3970, 0.8267, 0.4072, 0.6491, 0.9266, 0.5770, 0.4905]])


In [48]:
k = x.view(8,2) # 8x2 lik matrise donustu
print(k)

tensor([[0.1144, 0.6809],
        [0.3633, 0.0272],
        [0.5512, 0.6424],
        [0.2738, 0.9107],
        [0.4596, 0.3970],
        [0.8267, 0.4072],
        [0.6491, 0.9266],
        [0.5770, 0.4905]])


In [34]:
a = torch.ones(10)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
b = a.numpy() # tensor numpy dizisine doonustu
print(b)
type(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


numpy.ndarray

In [37]:
a.add_(1) # CPU uzerinde calisiyorsa a ve b ayni anda degisir.
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [39]:
x = np.ones(5)
y = torch.from_numpy(x)
print(x)
print(type(x))
print(y)
print(type(y))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [40]:
x +=1
print(x)
print(y)
#varsayilan olarak hepsi CPU'da calisir.

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
